import Head from 'next/head'
import Header from '../components/header'

export default function Home() {

  const cssContainer = "flex items-center w-screen h-60"
  const cssH1 ="text-2xl text-black"

  return (
    <>
      <Head>
        <title>Swarmtrust</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="box-border flex p-0 m-0">
        <Header />
        <div className="pt-16 w-screen h-auto bg-gray-500">
          <div className="w-screen ">
          <h1 className={cssH1}>Hello World</h1>
          <h1 className={cssH1}>hallo</h1>
          </div>
          
          <div className={cssContainer}>
            <h1 className={cssH1}>Watch Out Together</h1>
          </div>
          <div className={cssContainer}>
            <h1 className={cssH1}>Certification</h1>
          </div>
        
        </div>
      </main>
    </>
  )
}
