import * as React from 'react';
import Head from 'next/head'
import Header from '../components/header'
import Showroom from '../components/showroom'
import {Trait} from '../components/traits'

export default function WatchOutTogether() {
  const [defaultText, setDefaultText] = React.useState<string>('')
  const text:string = "Hallo"

  const setInfoText = () =>{
    setDefaultText(text)
  }

  function changePoap(trait1:string, trait2:string, trait3:string) {


  }

  return (
    <>
      <Head>
        <title>Swarmtrust | Watch out together</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />
      <div className="flex">
          <div className="flex flex-col pt-16 w-2/3 h-screen bg-gray-500">
            <div className="text-white">
              <Showroom/>
            </div>
            <div className="text-white">

                <p>{defaultText}</p>
            </div>

          </div>
          <div className="pt-16 w-1/3 h-screen bg-gray-500 opacity-95">
            <Trait/>
          </div>

        
      </div>
      </main>

      <script src="three.min.js"></script>
    </>
  )
}
