import {useRouter} from 'next/router'
import Head from 'next/head'
import Header from '../../components/header'
import { addAffiliate} from '@/firebase/controller'
import { useState } from 'react'



export default function Mint() {
  const router = useRouter()
  const result = router.query.tokenId
  const [affiliateNumber, setAffiliateNumber] = useState<number>(1)
  const tokenId:number = parseInt(result as string, 10)

console.log(tokenId)
  
interface MyDictionary {
  hash: string;
  from: string;
} 

async function handleFirebaseClick(){
    
  const response2:MyDictionary = {
    hash: "rdhsh",
    from: "erahseh"
  }
  
  const hash:string = response2.hash
  const from:string = response2.from
  console.log("TEST",hash)
  console.log(response2)
  console.log("TEST",from)

  addAffiliate({
    tokenId: tokenId,
    hash: hash,
    from: from,
    valid: false,
  });
}



  while(isNaN(tokenId)){

    return (
        <h1>Loading</h1>
        //Show Loading Page for 1 Second
        //After that Error Page
    )
  }
  
  if(tokenId <0 || tokenId >100){
    return (
        <h1>Error Token existiert nicht!</h1>
        //Show Error Page: "Token existiert nicht"
        //Token wurde noch nicht geminted
    )
  }
  return (
    <>
      <Head>
        <title>Swarmtrust | Mint </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
          <Header/>
          <div className="relative flex flex-col justify-center items-center pt-16">
          <h1 className="">TokenID: {tokenId}</h1>
          </div>
          <button
          className="w-40 h-12  text-white bg-green-500 rounded-lg opacity-75 hover:opacity-100"
          onClick={handleFirebaseClick}>Füge TokenId: {tokenId} hinzu</button>
            

        
      </main>
    </>
  )
}

