import {useRouter} from 'next/router'
import Head from 'next/head'
import styles from '../../styles/Mint.module.scss'
import Header from '../../components/header'
import { addAffiliate} from '@/firebase/controller'
import { useState } from 'react'



export default function Mint() {
  const router = useRouter()
  const result = router.query.tokenId
  const [affiliateNumber, setAffiliateNumber] = useState<number>(1)
  const tokenId:number = parseInt(result as string, 10)

console.log(tokenId)
  

  async function testFirebase(){
    addAffiliate({
      affiliateNumber,
      tokenId,
    });
  }


  while(isNaN(tokenId)){

    return (
        <h1>Loading</h1>
        //Show Loading Page for 1 Second
        //After that Error Page
    )
  }
  
  if(tokenId <0 || tokenId >100){
    return (
        <h1>Error Token existiert nicht!</h1>
        //Show Error Page: "Token existiert nicht"
        //Token wurde noch nicht geminted
    )
  }
  return (
    <>
      <Head>
        <title>Swarmtrust | Mint </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.body}>
          <Header/>
          <div className={styles.main}>
          <h1 className={styles.h1}>TokenID: {tokenId}</h1>
          </div>
          <button
          className={styles.button}
          onClick={testFirebase}>Füge TokenId: {tokenId} hinzu</button>
            

        
      </main>
    </>
  )
}

